<a href="https://colab.research.google.com/github/Parul-gargg/Numpy-Learning/blob/main/array_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**NUMPY INDEXING AND SLICING OF** **VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6] # this shows indexing at 6th number

np.int64(17)

In [ ]:
arr[1:6] # this is slicing

array([12, 13, 14, 15, 16])

In [ ]:
arr_slice =arr[3::2] # this shows slicing with steping of 2
arr_slice

array([14, 16, 18, 20])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [4]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr[5,4] # yahan 5 th row indexing and 4th column indexing

np.int64(30)

In [7]:
slice = arr[0:2,1:3] # this shows slicing from row 0:2 and column 1:3

In [9]:
slice_1=arr[3:,3:]

In [10]:
arr[:,2] # pura column chahiye to : laga ke , and konsa column 2

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN** **INDEXING**

In [11]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [15]:
arr = np.arange(11,21) # Re-initialize arr to its original state
bool_index = arr %2 == 0 # Re-create bool_index based on the re-initialized arr
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])