<a href="https://colab.research.google.com/github/Parul-gargg/Numpy-Learning/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

****ARRAY OPERATIONS****

*Arithmetic* *operations*

In [7]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [10]:
arr2 = a1 + a2
arr2                        # both list should have equal numbers then only operations can perform

array([ 7,  9, 11, 13, 15])

In [11]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [12]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [13]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [14]:
a1 // a2

array([0, 0, 0, 0, 0])

In [15]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [16]:
arr2 *2

array([14, 18, 22, 26, 30])

*Broadcasting*

In [17]:
l = [10,20,30,40]
arr = np.array(l)

In [18]:
arr + 10

array([20, 30, 40, 50])

In [19]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep* *and* *Shallow* *copy*

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
slice = a[:5]
slice


array([1, 2, 3, 4, 5])

In [27]:
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [28]:
a[4:6] * 10


array([50, 60])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
a
b = a

In [31]:
b[0] = 99

In [32]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

if you want ki a mai changes na ho then we use copy


In [34]:
a
b = a.copy()

In [35]:
b[0] =88
b

array([88,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

*Matrix* *operations*

In [40]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A
B

array([[5, 6],
       [7, 8]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
A @ B # multiplication of row and colums 1*5 +2*7, 1*6 + 2*8, 3*5 + 4*7, 3*6 + 4*8

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [45]:
# transpose row to column

In [46]:
A

array([[1, 2],
       [3, 4]])

In [47]:
A.T

array([[1, 3],
       [2, 4]])

***Advance*** ***Array*** ***Manipulation***


*Stacking* *Array*

In [51]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a
b

#there are 3 types of stack - vertical, horizontal and simple.
#we can stack only vectors not matrix

array([5, 6, 7, 8])

In [52]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting* *array*

In [55]:
 c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [58]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]