<a href="https://colab.research.google.com/github/Parul-gargg/Numpy-Learning/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Basic Array creation**

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3.5,'hello'] # example of list
a

[1, 2, 3.5, 'hello']

In [5]:
np.array(a) # array mai sab kuch ek jaisa hi print hoga like string

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
a = [1,2,3.5]  # yahan sab float mai print ho gaya
np.array(a)

array([1. , 2. , 3.5])

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]] # this is a list but when we run it in array we will see it becomes two dimensional list
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array generation function**

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr = np.zeros(6) # one dimensional
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((4,8)) # matrix horizontal are rows and verticals are column
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
arr = np.linspace(1,5,3) #linear space means 3 digit chahiye in between these two with equal space
arr

array([1., 3., 5.])

In [19]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**Random Generation function**

In [20]:
np.random.rand(10) # random library inbuilt hoti hai

array([0.86114647, 0.65121977, 0.36291211, 0.50211253, 0.41140212,
       0.5407439 , 0.352429  , 0.59305811, 0.0321752 , 0.60209047])


Note : jab values 0 and 1 ke beech mai ati hai to vo statistics mai normalization kahlata hai
and jab values 3 and -3 ke beech mai ati hain to vo standarization kahlata hai

In [21]:
np.random.randn(10)

array([ 1.74956379, -0.35068227, -1.1743006 , -1.21726689,  0.25458855,
        1.34304504,  0.82481153,  3.07373455, -1.07493702,  0.43719861])

In [22]:
np.random.randint(10,20,10) #agar points mai nai chahiye to integer function lagega

array([10, 10, 19, 19, 17, 14, 19, 16, 19, 11])

**Array** **Attributes**

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.shape # attributes mai hm () parentheses nai lagate hain

(3, 3)

In [25]:
arr.size

9

In [26]:
arr.dtype

dtype('int64')

**Array** **Methods**

In [ ]:
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [27]:
arr.min()

np.int64(1)

In [28]:
arr.max()

np.int64(9)

In [29]:
arr.sum()

np.int64(45)

In [30]:
#axis 0 verical (columns) and axis 1 horizontal (rows)

np.sum(arr,axis=0)

array([12, 15, 18])

In [31]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [32]:
arr.mean()

np.float64(5.0)

In [33]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmax() #Return the index (position) of the largest value in the array.

np.int64(8)

In [35]:
arr.argmin()

np.int64(0)

**Reshaping** **and** **resizing**

In [36]:
arr = np.arange(1,31)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
arr = arr.reshape(6,5) #convert this into 2 D matrix total counts ane chahiye 6*5 = 30

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])